### ISSUE TITLE
Will you publish the code?

### ISSUE THREAD

**Issue by Ciao121** [Zephyr1338/slither.io-bot#1]
As in the title :)

**Comment by Zephyr1338** [comment]
The code will probably published, unless I end up cancelling the project due to any attacks by Miniclip, or I decide that the code shouldn't be. But currently I do plan to release the code.

**Comment by Ciao121** [comment]
I don't think slither.io is owned by miniclip (yet).

**Comment by ItzLevvie** [comment]
Miniclip doesn't own slither.io

**Comment by Zephyr1338** [comment]
@ItzLevvie Oh I thought they did since it's on miniclip.
