### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by Qasimmodo** [Zephyr1338/slither.io-bot#2]
What are the commands to start the bots, and what are the necessary files?

**Comment by MasonBurdette** [comment]
From what I know this isn't a bot. It is a library to make your own.

**Comment by Qasimmodo** [comment]
So... what's the aim of the project? to make a library for people to use to make their own bots?

**Comment by MasonBurdette** [comment]
@Qasimmodo that's what i said...

**Comment by Zephyr1338** [comment]
Yeah, it's a library.
