### ISSUE TITLE
People who wish to join the project

### ISSUE THREAD

**Issue by Zephyr1338** [Zephyr1338/slither.io-bot#3]
If you want to join this project, you need to create a script to get slither.io servers, show the part which is decrypting the server infomration, in node.js preferably.

<img src="http://i.imgur.com/A9I6w9J.png" />
<i>List of servers</i>

**Comment by MasonBurdette** [comment]
ws = new WebSocket("ws://" + bso.ip + ":" + bso.po + "/slither");
(found where it creates the new websocket)

now all i need is to find where bso.ip and bso.po is requested from.. (is that right?)

**Comment by Zephyr1338** [comment]
@MasonBurdette bso.ip is coming from a list that's all I'll say.

**Comment by kmcgurty** [comment]
Easy enough

![](http://puu.sh/ouDQW/faff522c95.png)

![](http://puu.sh/ouDWU/65f66e3b82.png)

**Comment by MasonBurdette** [comment]
@kmcgurty u beat me to it 😠

**Comment by kmcgurty** [comment]
@MasonBurdette Wasn't too hard, just a few ctrl+f's in the source file to find "/i49526.txt" and then a few more to find the decryption.

**Comment by MasonBurdette** [comment]
@Zephyr1338 bro make an NPM account quick, so u can upload this

**Comment by Zephyr1338** [comment]
@kmcgurty Do you have any references to prove you won't leak the code?

**Comment by kmcgurty** [comment]
Not really, I guess you would just have to trust me. If you have a Steam, you can send me a friend request and we can talk there
