### ISSUE TITLE
How do people contact you?

### ISSUE THREAD

**Issue by Ciao121** [Zephyr1338/slither.io-bot#4]
I can't find a way to do this via github...

**Comment by Zephyr1338** [comment]
Via issues

**Comment by Ciao121** [comment]
But you wrote about "offers of money by people" but i do not see anything about that in issues...

**Comment by Zephyr1338** [comment]
@Ciao121 It was via skype.

**Comment by Ciao121** [comment]
And how to find your skype address?

**Comment by Zephyr1338** [comment]
My github name is my skype name
